=== BoboFraggins/ox/misc/ox.dtd
<!--
   a attribute is an attribute name usually beginning with the @ character
   i attribute is the id of the object if circular references are used
-->
<!ENTITY % common_attrs
         "a CDATA #IMPLIED
          i IDREF #IMPLIED" >

<!ENTITY % any "(a*, b*, c*, f*, g*, h*, i*, j*, l*, m*, n*, o*, p*, r*, s*, t*, u*, v*, x*, y*, z*)*">

<!ELEMENT o %any;>
<!ATTLIST o
          %common_attrs;
          c CDATA #REQUIRED> <!-- c attribute identifies the class of the serialized object -->

<!ELEMENT a %any;> <!-- Array -->
<!ATTLIST a %common_attrs;>

<!ELEMENT b (#PCDATA)> <!-- Base64 encoded String -->
<!ATTLIST b %common_attrs;>

<!ELEMENT c (#PCDATA)> <!-- Class -->
<!ATTLIST c %common_attrs;>

<!ELEMENT f (#PCDATA)> <!-- Float -->
<!ATTLIST f %common_attrs;>

<!ELEMENT g (#PCDATA)> <!-- Regexp -->
<!ATTLIST g %common_attrs;>

<!ELEMENT h %any;> <!-- Hash -->
<!ATTLIST h %common_attrs;>

<!ELEMENT i (#PCDATA)> <!-- Fixnum in base 10, e.g., -1234 -->
<!ATTLIST i %common_attrs;>

<!ELEMENT j (#PCDATA)> <!-- Bignum -->
<!ATTLIST j %common_attrs;>

<!ELEMENT l (#PCDATA)> <!-- Rational -->
<!ATTLIST l %common_attrs;>

<!ELEMENT m (#PCDATA)> <!-- Symbol -->
<!ATTLIST m %common_attrs;>

<!ELEMENT n EMPTY> <!-- False -->
<!ATTLIST n %common_attrs;>

<!ELEMENT p (#PCDATA)> <!-- Ref -->
<!ATTLIST p %common_attrs;>

<!ELEMENT r (#PCDATA)> <!-- Range -->
<!ATTLIST r %common_attrs;>

<!ELEMENT s (#PCDATA)> <!-- String -->
<!ATTLIST s %common_attrs;>

<!ELEMENT t (#PCDATA)> <!-- Time -->
<!ATTLIST t %common_attrs;>

<!ELEMENT u %any;> <!-- Struct -->
<!ATTLIST u %common_attrs;>

<!ELEMENT v (#PCDATA)> <!-- Complex -->
<!ATTLIST v %common_attrs;>

<!ELEMENT x (#PCDATA)> <!-- Raw XML embedded document -->
<!ATTLIST x %common_attrs;>

<!ELEMENT y EMPTY> <!-- True -->
<!ATTLIST y %common_attrs;>

<!ELEMENT z EMPTY> <!-- Nil -->
<!ATTLIST z %common_attrs;>

=== BoboFraggins/ox/misc/sample.xml
<?xml version="1.0"?>
<?ox mode="object" effort="strict" circular="false" xsd_date="false" ?>
<!DOCTYPE o SYSTEM "ox.dtd">
<o c="Test::Ox::Dir">
  <s a="@name">..</s>
  <t a="@ctime">1309872137.000000</t>
  <t a="@mtime">1309872137.000000</t>
  <i a="@size">510</i>
  <s a="@owner">ohler</s>
  <s a="@group">staff</s>
  <h a="@permissions">
    <m>user</m>
    <s>rwx</s>
    <m>group</m>
    <s>r-x</s>
    <m>other</m>
    <s>r-x</s>
  </h>
  <a a="@files">
    <o c="Test::Ox::Dir">
      <s a="@name">doc</s>
      <t a="@ctime">1302099563.000000</t>
      <t a="@mtime">1302099563.000000</t>
      <i a="@size">68</i>
      <s a="@owner">ohler</s>
      <s a="@group">staff</s>
      <h a="@permissions">
        <m>user</m>
        <s>rwx</s>
        <m>group</m>
        <s>r-x</s>
        <m>other</m>
        <s>r-x</s>
      </h>
      <a a="@files"/>
    </o>
    <o c="Test::Ox::Dir">
      <s a="@name">ext</s>
      <t a="@ctime">1302099552.000000</t>
      <t a="@mtime">1302099552.000000</t>
      <i a="@size">102</i>
      <s a="@owner">ohler</s>
      <s a="@group">staff</s>
      <h a="@permissions">
        <m>user</m>
        <s>rwx</s>
        <m>group</m>
        <s>r-x</s>
        <m>other</m>
        <s>r-x</s>
      </h>
      <a a="@files">
        <o c="Test::Ox::Dir">
          <s a="@name">ox</s>
          <t a="@ctime">1309874864.000000</t>
          <t a="@mtime">1309874864.000000</t>
          <i a="@size">1020</i>
          <s a="@owner">ohler</s>
          <s a="@group">staff</s>
          <h a="@permissions">
            <m>user</m>
            <s>rwx</s>
            <m>group</m>
            <s>r-x</s>
            <m>other</m>
            <s>r-x</s>
          </h>
          <a a="@files">
            <o c="Test::Ox::File">
              <s a="@name">base64.c</s>
              <t a="@ctime">1302604726.000000</t>
              <t a="@mtime">1302604726.000000</t>
              <i a="@size">4536</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">base64.h</s>
              <t a="@ctime">1302604726.000000</t>
              <t a="@mtime">1302604726.000000</t>
              <i a="@size">1919</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">base64.o</s>
              <t a="@ctime">1309873370.000000</t>
              <t a="@mtime">1309873370.000000</t>
              <i a="@size">6100</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">cache.c</s>
              <t a="@ctime">1302604726.000000</t>
              <t a="@mtime">1302604726.000000</t>
              <i a="@size">5211</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">cache.h</s>
              <t a="@ctime">1302604726.000000</t>
              <t a="@mtime">1302604726.000000</t>
              <i a="@size">1877</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">cache.o</s>
              <t a="@ctime">1309873370.000000</t>
              <t a="@mtime">1309873370.000000</t>
              <i a="@size">8764</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">cache16.z</s>
              <t a="@ctime">1302099552.000000</t>
              <t a="@mtime">1302099552.000000</t>
              <i a="@size">2596</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">cache8.c</s>
              <t a="@ctime">1302604726.000000</t>
              <t a="@mtime">1302604726.000000</t>
              <i a="@size">1844</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">cache8.h</s>
              <t a="@ctime">1302604726.000000</t>
              <t a="@mtime">1302604726.000000</t>
              <i a="@size">1915</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">cache8.o</s>
              <t a="@ctime">1309873370.000000</t>
              <t a="@mtime">1309873370.000000</t>
              <i a="@size">11272</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">cache8_test.c</s>
              <t a="@ctime">1302604726.000000</t>
              <t a="@mtime">1302604726.000000</t>
              <i a="@size">2542</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">cache8_test.o</s>
              <t a="@ctime">1309873370.000000</t>
              <t a="@mtime">1309873370.000000</t>
              <i a="@size">3952</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">cache_test.c</s>
              <t a="@ctime">1302604726.000000</t>
              <t a="@mtime">1302604726.000000</t>
              <i a="@size">2493</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">cache_test.o</s>
              <t a="@ctime">1309873370.000000</t>
              <t a="@mtime">1309873370.000000</t>
              <i a="@size">4856</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">dump.c</s>
              <t a="@ctime">1309866269.000000</t>
              <t a="@mtime">1309866269.000000</t>
              <i a="@size">26622</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
                <s>rw-</s>
                <m>group</m>
                <s>r--</s>
                <m>other</m>
                <s>r--</s>
              </h>
            </o>
            <o c="Test::Ox::File">
              <s a="@name">dump.o</s>
              <t a="@ctime">1309873371.000000</t>
              <t a="@mtime">1309873371.000000</t>
              <i a="@size">63344</i>
              <s a="@owner">ohler</s>
              <s a="@group">staff</s>
              <h a="@permissions">
                <m>user</m>
